# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('violent', models.CharField(blank=True, max_length=255, null=True)),
                ('prop', models.CharField(blank=True, max_length=255, null=True)),
                ('murder', models.CharField(blank=True, max_length=255, null=True)),
                ('rape', models.CharField(blank=True, max_length=255, null=True)),
                ('robbery', models.CharField(blank=True, max_length=255, null=True)),
                ('assault', models.CharField(blank=True, max_length=255, null=True)),
                ('burglary', models.CharField(blank=True, max_length=255, null=True)),
                ('theft', models.CharField(blank=True, max_length=255, null=True)),
                ('gta', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
